#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
sudo apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
sudo apt-get -y update
# Install HAProxy
apt-get install haproxy=2.7.\*
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen 68534-lb-01\n\tbind 0:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 68534-web-01 54.162.0.199:80 check\n\tserver 68534-web-02 100.25.24.66:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
