#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "
listen 68534-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 68534-web-01 54.162.0.199 check port 80
        server 68534-web-02 100.25.24.66 check port 80
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
