#!/usr/bin/env bash
# script that configures a server to listen to port 80
apt-get -y update
apt-get -y install nginx
service nginx start
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
service nginx restart
