#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

HOUR=0
while [ $HOUR -le 12 ]
do
	echo "Hour: $HOUR"
	MINUTES=1
	while [ $MINUTES -lt 60 ]
	do
		echo "$MINUTES"
		((MINUTES++))
	done
	((HOUR++))
done
